# Generated by Django 4.2.3 on 2023-11-09 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0006_allsports'),
        ('sportsquiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sportsquizcategory',
            options={'ordering': ['-id']},
        ),
        migrations.AlterUniqueTogether(
            name='sportsquizcategory',
            unique_together={('sport', 'all_sports')},
        ),
        migrations.AlterModelTable(
            name='sportsquizcategory',
            table='Sports Quiz Category',
        ),
    ]
