# Generated by Django 4.2.3 on 2023-08-14 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SportFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('playing_area', models.CharField(max_length=100)),
                ('equipments_required', models.TextField()),
                ('history', models.TextField()),
                ('rules', models.TextField()),
                ('image', models.ImageField(upload_to='sports/')),
                ('number_of_players', models.PositiveIntegerField(default=1)),
                ('category', models.CharField(choices=[('Indore', 'Indore'), ('Outdoor', 'Outdoor')], max_length=50)),
                ('governing_body', models.CharField(max_length=100)),
                ('forrmat_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.sportformat')),
            ],
        ),
    ]
