# Generated by Django 4.2.3 on 2023-08-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_alter_sport_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='category',
            field=models.CharField(choices=[('Indoor', 'Indoor'), ('Outdoor', 'Outdoor'), ('Dual-Sport', 'Dual-Sport')], max_length=50),
        ),
    ]
