# Generated by Django 4.2.3 on 2023-10-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllPlayersList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cricbuzz_id', models.IntegerField(unique=True, verbose_name='Cricbuzz Id')),
                ('player_name', models.CharField(max_length=500, verbose_name='Player Name')),
                ('team_name', models.CharField(max_length=500, verbose_name='Team Name')),
                ('face_image_id', models.IntegerField(unique=True, verbose_name='Face Image Id')),
            ],
        ),
    ]
