# Generated by Django 4.2.3 on 2023-10-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricbuzz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allplayerslist',
            options={'ordering': ['cricbuzz_id'], 'verbose_name': 'All Players List', 'verbose_name_plural': 'All Players List'},
        ),
        migrations.AlterField(
            model_name='allplayerslist',
            name='cricbuzz_id',
            field=models.PositiveBigIntegerField(unique=True, verbose_name='Cricbuzz Id'),
        ),
        migrations.AlterField(
            model_name='allplayerslist',
            name='face_image_id',
            field=models.PositiveBigIntegerField(unique=True, verbose_name='Face Image Id'),
        ),
    ]
