# Generated by Django 4.2.3 on 2023-10-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricbuzz', '0002_alter_allplayerslist_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allplayerslist',
            name='face_image_id',
            field=models.PositiveBigIntegerField(default=182026, verbose_name='Face Image Id'),
        ),
    ]
