# Generated by Django 4.2.3 on 2023-11-01 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricbuzz', '0004_internationalteams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internationalteams',
            name='country_name',
            field=models.CharField(max_length=500, null=True, verbose_name='Country Name'),
        ),
    ]
