# Generated by Django 4.2.3 on 2023-11-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricbuzz', '0005_alter_internationalteams_country_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internationalteams',
            name='country_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Country Name'),
        ),
    ]
