# Generated by Django 4.2.3 on 2023-08-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaveAllIndianSportsNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('published_at', models.CharField(max_length=500)),
                ('url', models.URLField()),
                ('url_to_image', models.URLField()),
                ('content', models.TextField()),
            ],
        ),
    ]
