# Generated by Django 4.2.3 on 2023-08-26 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsnews', '0002_alter_saveallindiansportsnews_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveallindiansportsnews',
            name='description',
            field=models.TextField(default='No Description Found'),
        ),
    ]
