# Generated by Django 4.2.3 on 2023-08-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsnews', '0006_alter_saveallindiansportsnews_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveallindiansportsnews',
            name='author',
            field=models.CharField(blank=True, default='No Author Found', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='saveallindiansportsnews',
            name='published_at',
            field=models.CharField(blank=True, default='No Published Date Found', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='saveallindiansportsnews',
            name='source_name',
            field=models.CharField(blank=True, default='No Title Found', max_length=1000, null=True),
        ),
    ]
