# Generated by Django 4.2.3 on 2023-08-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=2000)),
                ('image', models.ImageField(upload_to='about/')),
                ('point_one', models.TextField()),
                ('point_two', models.TextField()),
                ('point_three', models.TextField()),
            ],
        ),
    ]
